import { Video } from 'components/video/VideoCardList';
import { Movie } from 'components/movie/MovieCardList';

export const videos: Video[] = [
  {
    id: 1,
    title: 'hi1',
    desc: 'hi1',
    uploader: 'hi1',
    views: 10,
    createdAt: '2021-01-01',
    thumbnailSrc: '',
    thumbnailAlt: '',
    avatarSrc: '',
    avatarAlt: '',
  },
  {
    id: 2,
    title: 'hi1',
    desc: 'hi1',
    uploader: 'hi1',
    views: 10,
    createdAt: '2021-01-01',
    thumbnailSrc: '',
    thumbnailAlt: '',
    avatarSrc: '',
    avatarAlt: '',
  },
  {
    id: 3,
    title: 'hi1',
    desc: 'hi1',
    uploader: 'hi1',
    views: 10,
    createdAt: '2021-01-01',
    thumbnailSrc: '',
    thumbnailAlt: '',
    avatarSrc: '',
    avatarAlt: '',
  },
  {
    id: 4,
    title: 'hi1',
    desc: 'hi1',
    uploader: 'hi1',
    views: 10,
    createdAt: '2021-01-01',
    thumbnailSrc: '',
    thumbnailAlt: '',
    avatarSrc: '',
    avatarAlt: '',
  },
  {
    id: 5,
    title: 'hi1',
    desc: 'hi1',
    uploader: 'hi1',
    views: 10,
    createdAt: '2021-01-01',
    thumbnailSrc: '',
    thumbnailAlt: '',
    avatarSrc: '',
    avatarAlt: '',
  },
  {
    id: 6,
    title: 'hi1',
    desc: 'hi1',
    uploader: 'hi1',
    views: 10,
    createdAt: '2021-01-01',
    thumbnailSrc: '',
    thumbnailAlt: '',
    avatarSrc: '',
    avatarAlt: '',
  },
];

export const movies: Movie[] = [
  {
    id: 1,
    title: 'hi1',
    desc: 'hi1',
    provider: 'hi1',
    views: 10,
    createdAt: '2021-01-01',
    thumbnailSrc: '',
    thumbnailAlt: '',
  },
  {
    id: 2,
    title: 'hi1',
    desc: 'hi1',
    provider: 'hi1',
    views: 10,
    createdAt: '2021-01-01',
    thumbnailSrc: '',
    thumbnailAlt: '',
  },
  {
    id: 3,
    title: 'hi1',
    desc: 'hi1',
    provider: 'hi1',
    views: 10,
    createdAt: '2021-01-01',
    thumbnailSrc: '',
    thumbnailAlt: '',
  },
  {
    id: 4,
    title: 'hi1',
    desc: 'hi1',
    provider: 'hi1',
    views: 10,
    createdAt: '2021-01-01',
    thumbnailSrc: '',
    thumbnailAlt: '',
  },
  {
    id: 5,
    title: 'hi1',
    desc: 'hi1',
    provider: 'hi1',
    views: 10,
    createdAt: '2021-01-01',
    thumbnailSrc: '',
    thumbnailAlt: '',
  },
  {
    id: 6,
    title: 'hi1',
    desc: 'hi1',
    provider: 'hi1',
    views: 10,
    createdAt: '2021-01-01',
    thumbnailSrc: '',
    thumbnailAlt: '',
  },
];
